### ISSUE TITLE
Proofer::Confirmation#errors does not return a consistent type

### ISSUE THREAD

**Issue by monfresh** [18F/identity-proofer-gem#16]
Sometimes it returns nil, sometimes it returns an Array, sometimes a String. Please always return an array.

**Comment by monfresh** [comment]
Same with `Proofer::Resolution#errors`.

**Comment by pkarman** [comment]
`errors` should always return a `Hash` or `nil` -- is there some place specific you are seeing otherwise?

**Comment by monfresh** [comment]
Sorry, I was looking at the wrong thing. It's actually returning either nil or a Hash. If there are no errors, please return an empty Hash. Thanks!

**Comment by pkarman** [comment]
https://github.com/18F/identity-proofer-gem/pull/17

**Comment by pkarman** [comment]
fixed in #17
